config/routes.rb
Rails.application.routes.draw do
  
  
  root to: "products#index"
  devise_for :users
  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end
  resources :products do 
    resources :reviews
      collection do
        get :search_user
      end
    end
 
    resources :carts
    post 'carts/:id/add' => "carts#add", as: "cart_add"
    post 'carts/:id/reduce' => "carts#reduce", as: "cart_reduce"
end
     

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
      return unless user.present?
      can :read, Product
      return unless user.admin?
      can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates_uniqueness_of :product_id, scope: :user_id
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image
    belongs_to :user
    has_many :reviews, dependent: :destroy
    has_many :carts
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products
  has_many :reviews
  has_many :carts
  enum role: [:user,  :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
    private
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
    end
    

  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    
    def index
        if current_user.present?
        @carts = Cart.where(user_id: current_user.id)
        else
            redirect_to products_path, notice: 'please log in'
        end  
    end

    def create  
             
        @cart = current_user.carts.new(cart_params)
        if @cart.save
            redirect_to products_path, notice: 'added to cart' 
        else
            cart = Cart.find_by(product_id: params[:product_id])
            pro = Product.find(cart.product_id)  
            cart.update(quantity: (cart.quantity + 1), totalamount: (pro.price * (cart.quantity + 1)))
            redirect_to products_path, notice: 'quantity has been increased' 
        end

    end
    def destroy
        cart = Cart.find(params[:id])
        if cart.destroy
            redirect_to carts_path notice: 'product has been removed'
        
    
        end
    end
    def add
        cart = Cart.find(params[:id])
        pro = Product.find(cart.product_id)  
        cart.quantity += 1
        cart.save
        cart.update( totalamount: (pro.price * cart.quantity ))
        redirect_to carts_path
      end
      def reduce
        cart = Cart.find(params[:id])
        pro = Product.find(cart.product_id)  
        cart.quantity -= 1
        cart.save
        cart.update( totalamount: (pro.price * cart.quantity ))
        redirect_to carts_path
      end
    private
    def cart_params
        params.permit(:product_id, :totalamount )
      end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, :except => [:index, :show, :search_user ]
  # GET /products or /products.json
  def index
    
    if current_user && current_user.admin?
      @products = Product.where(user_id: current_user.id).paginate(page: params[:page], per_page: 2)
    else
      @products = Product.all.paginate(page: params[:page], per_page: 2)
      
    end

  end

  # GET /products/1 or /products/1.json
  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews.all
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = current_user.products.new(product_params)
    
    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  def search_user 
    @get_user = Product.where("name LIKE ? AND brand LIKE ?","#{params[:name]}%", "#{params[:brand]}%" )
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :title, :brand, :price, :image, )
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    load_resource :product, except: :index
    
    def index
        @product = Product.find(params[:product_id])
        @reviews = @product.reviews.all
    end
    def new
        @product = Product.find(params[:product_id])
        @review = @product.reviews.new
    end
    def create
        @review = @product.reviews.new(review_params)
        if @review.save
            redirect_to product_url(@product), notice: 'review has been submitted'
        else
            render :new
        end
    end
    def edit
        @product = Product.find(params[:product_id])
        @review = @product.reviews.find(params[:id])
    end
    def update
        @review = @product.reviews.find(params[:id])
        if @review.update(review_params)
            redirect_to product_url(@product), notice: 'review has been submitted'
        else
            render :edit
        end
    end

 def destroy
        @review = @product.reviews.find(params[:id])
        if @review.destroy
            redirect_to product_url(@product), notice: 'review has been deleted'
        else
            render :edit
        end
    end
    private 
    def review_params
        params.require(:review).permit(:description, :user_id, :product_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/index.html.erb
<% require "razorpay" %>
<% Razorpay.setup('rzp_test_2M1ZATQsmmZvpY', 'MgvyAEZ2ShGNMuWlURtTjvLJ') %>
<% @sum = 0%>
<% @carts.each do |cart| %>
  <p>
    <strong>Name:</strong>
    <%= Product.find(cart.product_id).name %>
  </p>
   <div>
   <%= image_tag(Product.find(cart.product_id).image)%>
   </div>
  <p>
    <strong>Title:</strong>
    <%= Product.find(cart.product_id).title %>
  </p>

  <p>
    <strong>Brand:</strong>
    <%= Product.find(cart.product_id).brand %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= Product.find(cart.product_id).price %>
  </p>
<div>
    <p>quantity :<%= cart.quantity %>  <%= button_to "+",  cart_add_url(cart), method: :post %>
    <%= button_to "-",  cart_reduce_url(cart), method: :post %> </p>
 </div>   
    <%= cart.totalamount %>
    <% @sum +=  cart.totalamount %> 
    <%= button_to "remove from cart", cart, method: :delete %>
<%end%>
<div>
  <strong>TotalAmount :</strong><%= @sum %>
</div>
<div>
<% if @sum > 1%>
<% order = Razorpay::Order.create amount: @sum, currency: 'INR', receipt: 'TEST' %>
<button id="rzp-button1">Pay with Razorpay</button>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
var options = {
    "key": "rzp_test_2M1ZATQsmmZvpY", // Enter the Key ID generated from the Dashboard
    "amount": "<%= order.amount%>", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
    "currency": "INR",
    "name": "Acme Corp",
    "description": "Test Transaction",
    "image": "https://example.com/your_logo",
    "order_id": "<%= order.id%>", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
    "handler": function (response){
        alert(response.razorpay_payment_id);
        alert(response.razorpay_order_id);
        alert(response.razorpay_signature)
    },
    "prefill": {
        "name": "Gaurav Kumar",
        "email": "gaurav.kumar@example.com",
        "contact": "9000090000"
    },
    "notes": {
        "address": "Razorpay Corporate Office"
    },
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);
rzp1.on('payment.failed', function (response){
        alert(response.error.code);
        alert(response.error.description);
        alert(response.error.source);
        alert(response.error.step);
        alert(response.error.reason);
        alert(response.error.metadata.order_id);
        alert(response.error.metadata.payment_id);
});
document.getElementById('rzp-button1').onclick = function(e){
    rzp1.open();
    e.preventDefault();
}
</script>
<% end %>
<%= link_to "Back to products", products_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecom</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>

      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %>
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :brand, style: "display: block" %>
    <%= form.text_field :brand %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>
   <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>


  <div>
    <%= form.submit %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

<% end %>

app/views/products/_product.html.erb
<div style="display:flex;align-items:center" id="<%= dom_id product %>">
 <div>
   <%= image_tag(product.image)%>
   </div>
   <div>
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>
  
  <p>
    <strong>Title:</strong>
    <%= product.title %>
  </p>

  <p>
    <strong>Brand:</strong>
    <%= product.brand %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>
  </div>
 <% if current_user.present?%>
  <%= button_to "Add to cart", carts_url(product_id: product.id, totalamount: product.price), method: :post %>
<% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>
 <%= link_to "go to cart", carts_path %>
<h1>Products</h1>

<%= form_with url: " /products/search_user", method: :get do |form| %>
  <%= form.text_field :name %>
  <%= form.text_field :brand %>
  <%= form.submit "Search" %>
<% end %>

</div>
<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
       
    </p>
  <% end %>
</div>
<%if can? :create, @product %>
<%= link_to "New product", new_product_path %>
<% end %>
<%= will_paginate %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/search_user.html.erb
<% @get_user.each do |pr| %>
<p>
    <strong>Name:</strong>
    <%= pr.name %>
  </p>
   <div>
   <%= image_tag(pr.image)%>
   </div>
  <p>
    <strong>Title:</strong>
    <%= pr.title %>
  </p>

  <p>
    <strong>Brand:</strong>
    <%= pr.brand %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= pr.price %>
  </p>
 <%= link_to "show this product", pr %> 
<% end %>
 <%= link_to "Back to products", products_path %>
  

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<p><strong>Reviews</strong></p>
<ul>
        <% @reviews.each do |re| %>
        <li><strong>given by  :</strong><%= User.find(re.user_id).email %>
            <br>
             <strong>description  :</strong><%= re.description  %>
             <br>
             <strong>Time  :</strong><%= re.created_at  %>
             <br>
            <% if current_user && re.user_id == current_user.id%>
             <%= link_to "Edit", edit_product_review_path(product_id: @product.id, id: re.id)%> 
             <%= button_to "Delete", product_review_path(product_id: @product.id, id: re.id),method: :delete, data: {confirm: 'are you sure remove this review'} %>
             <%end%>

             <hr>
             
             </li>

        <% end %>
   </ul>     

 
<div>
<%if can? :update, @product %>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
<% end %>
  <%= link_to "Back to products", products_path %>
  <% if current_user && current_user.role == "user" %>
   <%= link_to "add review", new_product_review_path(@product)  %>
   <%end%>
<%if can? :destroy, @product %>
  <%= button_to "Destroy this product", @product, method: :delete %>
<% end %>
</div>

app/views/reviews/edit.html.erb
<%= form_with model: [@product, @review] do |form| %>
     
        <div class = "col-lg-4">
           <div class = "form-group">
           <%= form.label :description, class: 'mb-2'%>
           <%= form.text_field :description,class: 'form-control,form-control-lg' %>
           
        </div>

    </div>
     <div class = "row">
      <div class = "col-lg-12 mt 4" >
      <%= form.submit class: 'btn btn-primary btn-lg rounded-0' %>
      </div>
      </div>
      <%= form.hidden_field :user_id, value: current_user.id %>
    <% end %>

app/views/reviews/index.html.erb
<ul>
        <% @reviews.each do |re| %>
        <li><%= re.description %></li>
        <% end %>
   </ul>     

            

app/views/reviews/new.html.erb
<%= form_with model: [@product, @review] do |form| %>
     
        <div class = "col-lg-4">
           <div class = "form-group">
           <%= form.label :description, class: 'mb-2'%>
           <%= form.text_field :description,class: 'form-control,form-control-lg' %>
           
        </div>

    </div>
     <div class = "row">
      <div class = "col-lg-12 mt 4" >
      <%= form.submit class: 'btn btn-primary btn-lg rounded-0' %>
      </div>
      </div>
      <%= form.hidden_field :user_id, value: current_user.id %>
    <% end %>